name: test
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting code
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install black and flake8
        run: python -m pip install black flake8
      - name: Lint using black
        run: python -m black --check pyrosm
      - name: Lint using flake8
        run: python -m flake8 pyrosm

  test:
    name: Run tests (${{ matrix.os }}, ${{ matrix.env }})
    needs: lint
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        env:
          - ci/37-conda.yaml
          - ci/38-conda.yaml
          - ci/39-conda.yaml
          - ci/310-conda.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          environment-file: ${{ matrix.env }}
          miniforge-version: latest
          miniforge-variant: Mambaforge
          auto-activate-base: false
          activate-environment: test
          channel-priority: strict

      - name: Install pyrosm
        shell: bash -l {0}
        run: pip install .

      - name: Check environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Test pyrosm
        shell: bash -l {0}
        run: pytest --cov --cov-report xml

      - name: Update codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
